
package trabalho.tp2_poo;

/**
 *
 * @author Fade
 */
public class CorreCabritoGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CorreCabritoGUI.class.getName());

    /**
     * Creates new form CorreCabritoGUI
     */
    public CorreCabritoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnTopo = new javax.swing.JButton();
        btnEsquerdaSuperior = new javax.swing.JButton();
        btnEsquerdaInferior = new javax.swing.JButton();
        btnCentro = new javax.swing.JButton();
        btnDireitaSuperior = new javax.swing.JButton();
        btnDireitaInferior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CorreCabrito");
        setIconImages(null);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTopo.setForeground(new java.awt.Color(60, 63, 65));
        btnTopo.setToolTipText("");
        btnTopo.setBorderPainted(false);
        btnTopo.setContentAreaFilled(false);
        btnTopo.addActionListener(this::btnTopoActionPerformed);
        jPanel2.add(btnTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, 70));

        btnEsquerdaSuperior.setToolTipText("");
        btnEsquerdaSuperior.setBorderPainted(false);
        btnEsquerdaSuperior.setContentAreaFilled(false);
        btnEsquerdaSuperior.addActionListener(this::btnEsquerdaSuperiorActionPerformed);
        jPanel2.add(btnEsquerdaSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 90, 70));

        btnEsquerdaInferior.setBackground(new java.awt.Color(255, 255, 255));
        btnEsquerdaInferior.setForeground(new java.awt.Color(60, 63, 65));
        btnEsquerdaInferior.setBorder(null);
        btnEsquerdaInferior.setBorderPainted(false);
        btnEsquerdaInferior.setContentAreaFilled(false);
        btnEsquerdaInferior.addActionListener(this::btnEsquerdaInferiorActionPerformed);
        jPanel2.add(btnEsquerdaInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 90, 70));

        btnCentro.setForeground(new java.awt.Color(255, 255, 255));
        btnCentro.setBorder(null);
        btnCentro.setBorderPainted(false);
        btnCentro.setContentAreaFilled(false);
        btnCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCentroMouseClicked(evt);
            }
        });
        btnCentro.addActionListener(this::btnCentroActionPerformed);
        jPanel2.add(btnCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 90, 70));

        btnDireitaSuperior.setBackground(new java.awt.Color(255, 255, 255));
        btnDireitaSuperior.setForeground(new java.awt.Color(60, 63, 65));
        btnDireitaSuperior.setBorder(null);
        btnDireitaSuperior.setBorderPainted(false);
        btnDireitaSuperior.setContentAreaFilled(false);
        btnDireitaSuperior.addActionListener(this::btnDireitaSuperiorActionPerformed);
        jPanel2.add(btnDireitaSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 90, 70));

        btnDireitaInferior.setBackground(new java.awt.Color(255, 255, 255));
        btnDireitaInferior.setForeground(new java.awt.Color(60, 63, 65));
        btnDireitaInferior.setBorder(null);
        btnDireitaInferior.setBorderPainted(false);
        btnDireitaInferior.setContentAreaFilled(false);
        btnDireitaInferior.addActionListener(this::btnDireitaInferiorActionPerformed);
        jPanel2.add(btnDireitaInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 90, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FundoIcon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopoActionPerformed

    private void btnEsquerdaSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquerdaSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsquerdaSuperiorActionPerformed

    private void btnEsquerdaInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquerdaInferiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsquerdaInferiorActionPerformed

    private void btnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCentroActionPerformed

    private void btnDireitaSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireitaSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDireitaSuperiorActionPerformed

    private void btnDireitaInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireitaInferiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDireitaInferiorActionPerformed

    private void btnCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseClicked

    }//GEN-LAST:event_btnCentroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CorreCabritoGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnDireitaInferior;
    private javax.swing.JButton btnDireitaSuperior;
    private javax.swing.JButton btnEsquerdaInferior;
    private javax.swing.JButton btnEsquerdaSuperior;
    private javax.swing.JButton btnTopo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
